### ISSUE TITLE
[MOBILE] Portfolio screenshots are too skinny

### ISSUE THREAD

**Issue by kesaxton** [kesaxton/astrellae.com#1]
### Thoughts
* Create organically wider images that have to be scaled on desktop?
* Serve smaller images on mobile breakpoint?
* Stretch image?
* Deal with it?

<img width="769" alt="error8" src="https://cloud.githubusercontent.com/assets/15181576/13376910/4187aadc-dd95-11e5-80ec-395a4c632f8d.png">

**Comment by kesaxton** [comment]
What do you think? @kingbryan

**Comment by kingbryan** [comment]
looks good to me!
