### ISSUE TITLE
[DESKTOP] Buttons have weird margins

### ISSUE THREAD

**Issue by kesaxton** [kesaxton/astrellae.com#3]
### Thoughts
* Explore scope of issue
* 3/10: Buttons/icons on homepage on mobile have weird margins too

<img width="758" alt="error15" src="https://cloud.githubusercontent.com/assets/15181576/13376959/7f34ed1c-dd96-11e5-90eb-e8d842b1a0a9.png">

**Comment by kesaxton** [comment]
@kingbryan please review all button margins (this specific one on contact page on desktop and all buttons on mobile)

**Comment by kingbryan** [comment]
I feel like there isn't enough margin on ONLY the contact form submit button. Just seems a little too close to the input above it, especially when you look at your other buttons.
