### ISSUE TITLE
Off-center headings in mobile view

### ISSUE THREAD

**Issue by kingbryan** [kesaxton/astrellae.com#5]
Maybe center align these headers when you get to mobile?

![mobile-off-center-headings](https://cloud.githubusercontent.com/assets/9124103/13692375/f960047e-e70e-11e5-99b3-1b792b8b9a86.png)

**Comment by kesaxton** [comment]
I gotcha, but what would be the max-width breakpoint for that? Like 800? Or whatever Bootstrap col sm is?

**Comment by kingbryan** [comment]
Yeah I think its like 768 or something.

**Comment by kingbryan** [comment]
Check this out: [https://getbootstrap.com/css/#grid](https://getbootstrap.com/css/#grid)

**Comment by kesaxton** [comment]
Please review.
