### ISSUE TITLE
Bootstrap rows break when viewport is squeezed

### ISSUE THREAD

**Issue by kingbryan** [kesaxton/astrellae.com#6]
When you squeeze the viewport, the tags for each project start to wrap to the next line. Consequentially, the heights of the divs become different and don't fit in the row.

![image](https://cloud.githubusercontent.com/assets/9124103/13692403/4cb0b77c-e70f-11e5-8dce-377bc2b1bf61.png)

**Comment by kesaxton** [comment]
That's a feature of Bootstrap though....masonry. What's the width when you got this?

**Comment by kingbryan** [comment]
820px wide.

**Comment by kesaxton** [comment]
Please review.

**Comment by kingbryan** [comment]
Perfff
