### ISSUE TITLE
SVG Font issues

### ISSUE THREAD

**Issue by kingbryan** [kesaxton/astrellae.com#7]
Your pretty fonts aren't rendering properly. Try using @font-face technique or just convert SVGs to path.

![image](https://cloud.githubusercontent.com/assets/9124103/13692484/d6521e26-e70f-11e5-9e20-ee8c5d6ee480.png)

**Comment by kesaxton** [comment]
I wonder why the E from the header isn't showing at all (not even that it's not the right font)...

**Comment by kesaxton** [comment]
Let me look into @font-face

**Comment by kesaxton** [comment]
Fixed. Please check (1) homepage greeting, (2) homepage CTA, (3-6) each title of the 4 pages, (7) faq on services page, and (8) logo.

**Comment by kingbryan** [comment]
Hmm not working for me. I can see the style declaration for font as Helena though. Is the font on your server?

**Comment by kesaxton** [comment]
ya, chrome doesn't support .otf

**Comment by kingbryan** [comment]
hmmmm does the font come in other formats?

**Comment by kesaxton** [comment]
I'm fixing it, hold on

**Comment by kesaxton** [comment]
Check it now!

**Comment by kingbryan** [comment]
Looks AMAZING!!! :100:
